<?php

class ETC_CmsCtf7_Widget extends Elementor_Theme_Core_Widget_Base{
    protected $name = 'cms_ctf7';
    protected $title = 'CMS Contact Form 7';
    protected $icon = 'eicon-form-horizontal';
    protected $categories = array( 'elementor-theme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/localhost\/unit-test\/wp-content\/themes\/saniga\/elementor\/templates\/widgets\/cms_ctf7\/layout-images\/1.png"},"2":{"label":"Layout 2","image":"http:\/\/localhost\/unit-test\/wp-content\/themes\/saniga\/elementor\/templates\/widgets\/cms_ctf7\/layout-images\/2.png"}},"prefix_class":"cms-cf7-layout-"}]},{"name":"source_section","label":"Source Settings","tab":"content","controls":[{"name":"form_title","label":"Form Title","type":"text","placeholder":"Request An Estimate","label_block":true},{"name":"form_desc","label":"Form Description","type":"textarea","placeholder":"For a cleaning that meets your highest standards, you need a dedicated team of trained specialists with all supplies needed to thoroughly clean your home.","label_block":true},{"name":"ctf7_id","label":"Select Form","type":"select","options":{"5":"Contact form 1"}}]},{"name":"image_section","label":"Banner Settings","tab":"content","controls":[{"name":"form_banner","label":"Choose your banner","type":"media","label_block":true,"condition":{"layout":["0"]}},{"name":"thumbnail_size","type":"image-size","control_type":"group","default":"full","condition":{"form_banner!":""}}],"condition":{"layout":["0"]}},{"name":"icon_section","label":"Icon Settings","tab":"content","controls":[{"name":"selected_icon","label":"Icon","type":"icons","fa4compatibility":"icon","default":{"value":"cmsi-paper-plane","library":"cmsi"}},{"name":"icon_size","type":"slider","range":{"px":{"min":20,"max":200}},"size_units":["px"],"default":{"unit":"px","size":50}}],"condition":{"layout":["0"]}},{"name":"rating_section","label":"Rate Settings","tab":"content","controls":[{"name":"show_rate","type":"switcher","label":"Show Rate","default":"true"},{"name":"rate_star","type":"media","label":"Star Icon","default":{"url":"http:\/\/localhost\/unit-test\/wp-content\/themes\/saniga\/assets\/images\/icons\/star-three.png"},"condition":{"show_rate":"true"}},{"name":"rate_star_bg","type":"color","label":"Star Icon Background","condition":{"show_rate":"true"}},{"name":"rate_value","label":"Percent Value","type":"slider","range":{"%":{"min":1,"max":100}},"size_units":["%"],"default":{"unit":"%","size":"97"},"condition":{"show_rate":"true"}},{"name":"rate_text","type":"textarea","label":"Rate Text","condition":{"show_rate":"true"}}],"condition":{"layout":["1"]}}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}